name: Update Docker Hub Readme

on:
  push:
    paths:
      - 'README.md'
  workflow_dispatch:
jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2.1.0
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        DOCKERHUB_REPOSITORY: peterevans/dockerhub-description
