name: Docker Hub Build

on:
  push:
    tags:
      - '*'
    paths-ignore:
      - '**/README.md'
      - '.github/**'
      - '.gitattributes'
      - '.gitignore'
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install Node.js Dependencies
        run: yarn install
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'all'
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/protect-timelapse:latest,${{ secrets.DOCKERHUB_USERNAME }}/protect-timelapse:${{ github.ref_name }},${{ secrets.DOCKERHUB_USERNAME }}/protect-timelapse:${{ github.sha }}
          
